#!/bin/bash
# Version numbering: major.minor.maintenance-arch_release
# pacman drops maintenance number if maintenance=0, e.g. 3.16.0-2 --> 3.16-2
u=$(uname -r); u=${u%-ARCH}; [[ $u = *.0-* ]] && u=${u/.0-/-}
p=$(pacman -Q linux|cut -d" " -f2)
q=${1-} 	# Shall I be quiet?
if [[ $u == $p ]]; then
	if [[ $q != '-q' ]]; then
		echo The installed and running kernels are the same, \([1m$u[0m\).
	fi
	exit 1
else
	if [[ $q != '-q' ]]; then
		echo Kernel installed: $p
		echo Kernel running:   $u
		echo Yes, you need reboot.
	fi
fi
